CREATE TABLE SPRINGBOARD
( NO INTEGER
, TITLE VARCHAR2(500)
, COUNT INTEGER
, CONTENT VARCHAR2(1000)
, W_DATE DATE
, ID VARCHAR2(500)
);

CREATE SEQUENCE springboard_seq;

CREATE TABLE SPRINGBOARD_UPLOAD
( NO INTEGER
, TITLE VARCHAR2(500)
, COUNT INTEGER
, W_DATE DATE
, CONTENT VARCHAR2(1000)
, ID VARCHAR2(500)
, ORGFILENAME VARCHAR2(500)
, NEWFILENAME VARCHAR2(500)
);

CREATE SEQUENCE SPRINGBOARD_UPLOAD_SEQ;

DROP TABLE SPRINGBOARD PURGE;