CREATE TABLE SPRINGBOARD
( NO INTEGER
, TITLE VARCHAR2(500)
, COUNT INTEGER
, CONTENT VARCHAR2(1000)
, W_DATE DATE
, ID VARCHAR2(500)
);

CREATE SEQUENCE springboard_seq;

DROP TABLE SPRINGBOARD PURGE;