CREATE TABLE MYPRODUCT
( ID INTEGER 
, NAME VARCHAR2(500)
, MAKER VARCHAR2(500)
, PRICE INTEGER
);

CREATE SEQUENCE MYPRODUCT_SEQ;

DELETE FROM MYPRODUCT;

DROP SEQUENCE MYPRODUCT_SEQ;

DROP TABLE MYPRODUCT PURGE;